version: "3.1"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    tty: true
    image: ethsigns-web
    environment:
      NODE_ENV: production
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
