version: "3.1"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    tty: true
    image: ethsigns-web
    environment:
      NODE_ENV: production
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_PRIVATE_KEY: ${REACT_APP_PRIVATE_KEY}
      REACT_APP_PUBLIC_KEY: ${REACT_APP_PUBLIC_KEY}
      REACT_APP_ALCHEMY_API_URL: ${REACT_APP_ALCHEMY_API_URL}
      REACT_APP_PINATA_API_JWT_TOKEN: ${REACT_APP_PINATA_API_JWT_TOKEN}
      REACT_APP_IPFS_API_URL: http://ipfs:5001
      REACT_APP_IPFS_GATEWAY_URL: ${REACT_APP_IPFS_GATEWAY_URL}
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - ipfs-network

  ipfs:
    image: ipfs/go-ipfs
    volumes:
      - ./ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "8080:8080"
      - "8081:8081"
      - "5001:5001"
    networks:
      - ipfs-network

networks:
  ipfs-network:
