version: "3"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    tty: true
    image: ethsigns-web
    environment:
      NODE_ENV: production
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_PRIVATE_KEY: ${REACT_APP_PRIVATE_KEY}
      REACT_APP_PUBLIC_KEY: ${REACT_APP_PUBLIC_KEY}
      REACT_APP_RPC_API_URL: ${REACT_APP_RPC_API_URL}
      REACT_APP_PINATA_API_JWT_TOKEN: ${REACT_APP_PINATA_API_JWT_TOKEN}
      REACT_APP_IPFS_API_KEY: ${REACT_APP_IPFS_API_KEY}
      REACT_APP_IPFS_API_URL: ${REACT_APP_IPFS_API_URL}
      REACT_APP_IPFS_GATEWAY_URL: ${REACT_APP_IPFS_GATEWAY_URL}
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
