version: "3"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    tty: true
    image: ethsigns-web
    environment:
      NODE_ENV: production
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_PUBLIC_KEY: ${REACT_APP_PUBLIC_KEY}
      REACT_APP_RPC_API_URL: ${REACT_APP_RPC_API_URL}
      REACT_APP_CONTRACT_ADDRESS: ${REACT_APP_CONTRACT_ADDRESS}
      REACT_APP_TRANSACTION_EXPLORER: ${REACT_APP_TRANSACTION_EXPLORER}
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
